version: '2'

services:

    mongo:
      image: mongo
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass
      container_name: mongo-db
      restart: always
      privileged: true

